// Generated by GraphWalker (http://www.graphwalker.org)
package com.filemanager.model;

import org.graphwalker.java.annotation.Edge;
import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;

@Model(file = "models/modelo-file-manager1.json")
public interface FileManager {

    @Edge()
    void e_OpenApp();

    @Edge()
    void e_CreateNewFolder();

    @Edge()
    void e_RenameFolder();

    @Vertex()
    void v_ListFolders();

    @Vertex()
    void v_NewFolder();

    @Edge()
    void e_DeleteFolder();

    @Vertex()
    void v_Start();

    @Vertex()
    void v_NewFile();

    @Edge()
    void e_CreateNewFile();

    @Edge()
    void e_DeleteFile();

    @Edge()
    void e_RenameFile();
}
