package com.gallery.model;

// Generated by GraphWalker (http://www.graphwalker.org)
import org.graphwalker.java.annotation.Edge;
import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;

@Model(file = "models/modelo-gallery1.json")
public interface AnimatedImageOptions {

    @Edge()
    void e_TypeNewName();

    @Edge()
    void e_ClickOnEditionIcon();

    @Vertex()
    void v_EditImage();

    @Vertex()
    void v_ShareImage();

    @Edge()
    void e_GoBackFromRename();

    @Edge()
    void e_ClickOnScreen();

    @Edge()
    void e_ClickOnImage();

    @Vertex()
    void v_RenameImage();

    @Edge()
    void e_ClickOnRenameIcon();

    @Edge()
    void e_ClickOnShareIcon();

    @Edge()
    void e_DiscardNewName();

    @Vertex()
    void v_CheckName();

    @Edge()
    void e_ClickOK();

    @Edge()
    void e_ClickOnInfoIcon();

    @Edge()
    void e_GoBackFromSharing();

    @Vertex()
    void v_OpenImageProperties();

    @Vertex()
    void v_ViewImageFullScreen();

    @Edge()
    void e_GoBackFromEdition();

    @Edge()
    void e_SaveNewName();

    @Vertex()
    void v_OpenAnimatedImage();
}
