package com.gallery.model;

// Generated by GraphWalker (http://www.graphwalker.org)
import org.graphwalker.java.annotation.Edge;
import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;

@Model(file = "modelo-gallery1.json")
public interface MainFlow {

    @Edge()
    void e_OpenApp();

    @Vertex()
    void v_ListFolders();

    @Vertex()
    void v_CheckPermissions();

    @Edge()
    void e_SelectStaticImage();

    @Edge()
    void e_GoBackFromAnimatedImage();

    @Edge()
    void e_GoBackFromVideo();

    @Vertex()
    void v_OpenVideo();

    @Edge()
    void e_GoBackFromStaticImage();

    @Vertex()
    void v_OpenStaticImage();

    @Edge()
    void e_EnablePermissions();

    @Edge()
    void e_SelectFolder();

    @Edge()
    void e_SelectAnimatedImage();

    @Edge()
    void e_GoBackFromFolderItems();

    @Edge()
    void e_RejectPermissions();

    @Vertex()
    void v_Start();

    @Vertex()
    void v_ListFolderItems();

    @Edge()
    void e_SelectVideo();

    @Vertex()
    void v_OpenAnimatedImage();
}
