package com.gallery.model;

// Generated by GraphWalker (http://www.graphwalker.org)
import org.graphwalker.java.annotation.Edge;
import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;

@Model(file = "models/modelo-gallery1.json")
public interface StaticImageOptions {

    @Vertex()
    void v_EditImage();

    @Vertex()
    void v_ShareImage();

    @Edge()
    void e_ClickOnScreen();

    @Edge()
    void e_ClickOnImage();

    @Edge()
    void e_ClickOnRoteteIcon();

    @Edge()
    void e_SelectRotation();

    @Edge()
    void e_ClickOnShareIcon();

    @Edge()
    void e_SaveChanges();

    @Vertex()
    void v_RotateImage();

    @Vertex()
    void v_OpenStaticImageOptions();

    @Edge()
    void e_ClickOK();

    @Edge()
    void e_ClickOnInfoIcon();

    @Edge()
    void e_GoBackFromSharing();

    @Vertex()
    void v_OpenImageProperties();

    @Edge()
    void e_DiscardChanges();

    @Vertex()
    void v_ViewImageFullScreen();

    @Edge()
    void e_GoBackFromEdition();

    @Edge()
    void e_ClickOnEditIcon();
}
