package com.gallery.model;

// Generated by GraphWalker (http://www.graphwalker.org)
import org.graphwalker.java.annotation.Edge;
import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;

@Model(file = "modelo-gallery1.json")
public interface VideoPlayerInterface {

    @Edge()
    void e_SelectSpeed();

    @Vertex()
    void v_OpenVideoPlayer();

    @Edge()
    void e_ClickOnUnmuteIcon();

    @Edge()
    void e_ClickOnScreen();

    @Edge()
    void e_ClickOnMuteIcon();

    @Edge()
    void e_SaveChanges();

    @Edge()
    void e_ClickOnVideo();

    @Edge()
    void e_ClickOnSpeedIcon();

    @Vertex()
    void v_ChangePlayStatus();

    @Vertex()
    void v_MuteAudio();

    @Edge()
    void e_ClickOnPauseIcon();

    @Edge()
    void e_ClickOnPlayIcon();

    @Vertex()
    void v_ViewFullScreen();

    @Edge()
    void e_DiscardChanges();

    @Vertex()
    void v_PlaybackSpeed();
}
