package com.gallery.model;

// Generated by GraphWalker (http://www.graphwalker.org)
import org.graphwalker.java.annotation.Edge;
import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;

@Model(file = "modelo-gallery1.json")
public interface VideoOptionsInterface {

    @Edge()
    void e_TypeNewName();

    @Edge()
    void e_GoBackFromRename();

    @Vertex()
    void v_OpenVideoPlayer();

    @Vertex()
    void v_RenameVideo();

    @Vertex()
    void v_EditVideo();

    @Edge()
    void e_ClickOnRenameIcon();

    @Edge()
    void e_ClickOnShareIcon();

    @Edge()
    void e_GoBackFromPlayer();

    @Vertex()
    void v_OpenVideoOptions();

    @Edge()
    void e_DiscardNewName();

    @Vertex()
    void v_CheckName();

    @Edge()
    void e_ClickOnPlayIcon();

    @Vertex()
    void v_OpenVideoProperties();

    @Edge()
    void e_ClickOK();

    @Vertex()
    void v_ShareVideo();

    @Edge()
    void e_GoBackFromSharing();

    @Edge()
    void e_ClickOnInfoIcon();

    @Edge()
    void e_GoBackFromEdition();

    @Edge()
    void e_SaveNewName();

    @Edge()
    void e_ClickOnEditIcon();
}
